SET @ROLE_GUEST = 1;
SET @ROLE_USER  = 2;
SET @ROLE_ADMIN = 3;

SET @PERMISSION_REGISTER        = 1;
SET @PERMISSION_COMMENT         = 2;
SET @PERMISSION_RATE            = 3;
SET @PERMISSION_VIEW_ADMIN_CP   = 4;
SET @PERMISSION_EDIT_CP_USER    = 5;
SET @PERMISSION_EDIT_RO_USER    = 6;
SET @PERMISSION_VIEW_SERVER_ACC = 7;
SET @PERMISSION_VIEW_ITEMS      = 8;
SET @PERMISSION_BAN_CP_USER     = 9;
SET @PERMISSION_BAN_RO_USER     = 10;
SET @PERMISSION_VIEW_CP_LOGS    = 11;
SET @PERMISSION_VIEW_RO_LOGS    = 12;
SET @PERMISSION_EDIT_CP_CONF    = 13;
SET @PERMISSION_EDIT_RO_CONF    = 14;
SET @PERMISSION_CREATE_PAGES    = 15;
SET @PERMISSION_CREATE_POSTS    = 16;
SET @PERMISSION_MANAGE_ROLES    = 17;
SET @PERMISSION_MANAGE_PLUGINS  = 18;

SET @CTYPE_POST = 1;
SET @CTYPE_PAGE = 2;

SET @PROFILE_HTML     = 1;
SET @PROFILE_BBCODE   = 2;
SET @PROFILE_MARKDOWN = 3;
SET @PROFILE_TEXT     = 4;

INSERT IGNORE INTO `#roles` VALUES
 (@ROLE_GUEST, 'Guest', NULL, NULL, 'y', 'n', NULL)
,(@ROLE_USER, 'User', NULL, NULL, 'y', 'y', NULL)
,(@ROLE_ADMIN, 'Administrator', '16723522', NULL, 'y', 'y', NULL)
;

REPLACE INTO `#permissions` VALUES
 (@PERMISSION_REGISTER, 'register-account', NULL)
,(@PERMISSION_COMMENT, 'comment', NULL)
,(@PERMISSION_RATE, 'rate', NULL)
,(@PERMISSION_VIEW_ADMIN_CP, 'view-admin-cp', NULL)
,(@PERMISSION_VIEW_SERVER_ACC, 'view-server-acc', NULL)
,(@PERMISSION_EDIT_CP_USER, 'edit-cp-user', NULL)
,(@PERMISSION_EDIT_RO_USER, 'edit-server-user', NULL)
,(@PERMISSION_VIEW_ITEMS, 'view-user-items', NULL)
,(@PERMISSION_BAN_CP_USER, 'ban-cp-user', NULL)
,(@PERMISSION_BAN_RO_USER, 'ban-server-user', NULL)
,(@PERMISSION_VIEW_CP_LOGS, 'view-cp-logs', NULL)
,(@PERMISSION_VIEW_RO_LOGS, 'view-server-logs', NULL)
,(@PERMISSION_EDIT_CP_CONF, 'edit-cp-settings', NULL)
,(@PERMISSION_EDIT_RO_CONF, 'edit-server-settings', NULL)
,(@PERMISSION_CREATE_PAGES, 'create-pages', NULL)
,(@PERMISSION_CREATE_POSTS, 'publish-posts', NULL)
,(@PERMISSION_MANAGE_ROLES, 'manage-roles', NULL)
,(@PERMISSION_MANAGE_PLUGINS, 'manage-plugins', NULL)
;

REPLACE INTO `#role_permissions` VALUES
 (@ROLE_USER, @PERMISSION_REGISTER, 'n')
,(@ROLE_USER, @PERMISSION_COMMENT, 'n')
,(@ROLE_USER, @PERMISSION_RATE, 'n')
,(@ROLE_ADMIN, @PERMISSION_REGISTER, 'y')
,(@ROLE_ADMIN, @PERMISSION_COMMENT, 'y')
,(@ROLE_ADMIN, @PERMISSION_RATE, 'y')
,(@ROLE_ADMIN, @PERMISSION_VIEW_ADMIN_CP, 'y')
,(@ROLE_ADMIN, @PERMISSION_VIEW_SERVER_ACC, 'y')
,(@ROLE_ADMIN, @PERMISSION_EDIT_CP_USER, 'y')
,(@ROLE_ADMIN, @PERMISSION_EDIT_RO_USER, 'y')
,(@ROLE_ADMIN, @PERMISSION_VIEW_ITEMS, 'y')
,(@ROLE_ADMIN, @PERMISSION_BAN_CP_USER, 'y')
,(@ROLE_ADMIN, @PERMISSION_BAN_RO_USER, 'y')
,(@ROLE_ADMIN, @PERMISSION_VIEW_CP_LOGS, 'y')
,(@ROLE_ADMIN, @PERMISSION_VIEW_RO_LOGS, 'y')
,(@ROLE_ADMIN, @PERMISSION_EDIT_CP_CONF, 'y')
,(@ROLE_ADMIN, @PERMISSION_EDIT_RO_CONF, 'y')
,(@ROLE_ADMIN, @PERMISSION_CREATE_PAGES, 'y')
,(@ROLE_ADMIN, @PERMISSION_CREATE_POSTS, 'y')
,(@ROLE_ADMIN, @PERMISSION_MANAGE_ROLES, 'y')
,(@ROLE_ADMIN, @PERMISSION_MANAGE_PLUGINS, 'y')
;

INSERT IGNORE INTO `#content_type` VALUES
 (@CTYPE_POST, 'news', 'Post', NULL, NULL, 'y', 'y', NULL)
,(@CTYPE_PAGE, 'page', 'Page', NULL, NULL, 'n', 'n', NULL)
;

TRUNCATE `#content_type_filters`;
INSERT INTO `#content_type_filters` VALUES
 (@CTYPE_POST, 'CategoryFilter', 'a:0:{}')
,(@CTYPE_POST, 'CommentFilter', 'a:0:{}')
,(@CTYPE_POST, 'FeaturedFilter', 'a:0:{}')
,(@CTYPE_POST, 'RatingFilter', 'a:0:{}')
,(@CTYPE_POST, 'ScheduleFilter', 'a:0:{}')
,(@CTYPE_POST, 'TagFilter', 'a:0:{}')
,(@CTYPE_POST, 'ArchiveFilter', 'a:0:{}')
,(@CTYPE_PAGE, 'RatingFilter', 'a:0:{}')
,(@CTYPE_PAGE, 'RelationshipFilter', 'a:0:{}')
;

INSERT IGNORE INTO `#content` VALUES
 (1, @CTYPE_PAGE, 1 , NULL, NOW(), NULL, 0, 'tos', 'Terms of Service', '', '', 'y', 0)
;
INSERT IGNORE INTO `#content_meta` VALUES
 (1, 'rating-disabled', 'b:1;')
;
